### ISSUE TITLE
Not working if install path is different from C:\

### ISSUE THREAD

**Issue by thnhmai06** [MikeCoder96/NotePad-Discord-Rich-Presence-Plugin#2]
![image](https://user-images.githubusercontent.com/62001770/171820173-088b4982-b728-464e-af00-5e57c624a385.png)

NotePad++ Ver: v8.3.3 (32-bit)

**Comment by MikeCoder96** [comment]
I will update in these days! Thanks for your report.

**Comment by MikeCoder96** [comment]
I haven't found this issue! Maybe you've forgot to add the libs inside the plugin folder. 
Here an how to:
- Go to plugin folder of Notepad++
- Create Folder with name "NotePad++RichDiscord"
- Paste inside NotePad++RichDiscord-x86.dll or NotePad++RichDiscord-x64.dll (Depends by your version of notepad++)
- Rename NotePad++RichDiscord-x86.dll or NotePad++RichDiscord-x64.dll with NotePad++RichDiscord.dll
- In the same folder create a folder with name "Lib"
- Inside the folder "Lib" paste DiscordRPC.dll and Newtonsoft.Json.dll

here some screenshot 
![image](https://user-images.githubusercontent.com/50410305/171951270-088637bc-8ede-4ebd-8fdc-397a7102044c.png)

![image](https://user-images.githubusercontent.com/50410305/171951300-51aed599-cb08-469d-9be3-a8c43ff138be.png)

![image](https://user-images.githubusercontent.com/50410305/171951318-af2cd809-076d-44eb-a4f8-b48b38a2816b.png)


Please, let me know!

**Comment by thnhmai06** [comment]
> I haven't found this issue! Maybe you've forgot to add the libs inside the plugin folder. Here an how to:
> 
> * Go to plugin folder of Notepad++
> * Create Folder with name "NotePad++RichDiscord"
> * Paste inside NotePad++RichDiscord-x86.dll or NotePad++RichDiscord-x64.dll (Depends by your version of notepad++)
> * Rename NotePad++RichDiscord-x86.dll or NotePad++RichDiscord-x64.dll with NotePad++RichDiscord.dll
> * In the same folder create a folder with name "Lib"
> * Inside the folder "Lib" paste DiscordRPC.dll and Newtonsoft.Json.dll
> 
> here some screenshot ![image](https://user-images.githubusercontent.com/50410305/171951270-088637bc-8ede-4ebd-8fdc-397a7102044c.png)
> 
> ![image](https://user-images.githubusercontent.com/50410305/171951300-51aed599-cb08-469d-9be3-a8c43ff138be.png)
> 
> ![image](https://user-images.githubusercontent.com/50410305/171951318-af2cd809-076d-44eb-a4f8-b48b38a2816b.png)
> 
> Please, let me know!

Thanks for your help, but it still doesn't seem to work

- Notepad++ Debug Information: 
```
Notepad++ v8.3.3   (32-bit)
Build time : Mar 13 2022 - 17:11:10
Path : D:\PROGRAM\Notepad++\notepad++.exe
Command Line : 
Admin mode : ON
Local Conf mode : OFF
Cloud Config : OFF
OS Name : Windows 10 Enterprise (64-bit) 
OS Version : 1903
OS Build : 18362.30
Current ANSI codepage : 1258
Plugins : mimeTools.dll NppConverter.dll NppExport.dll 
```

https://user-images.githubusercontent.com/62001770/172512078-0dc6ee96-d920-4634-b7af-9354107949e4.mp4

**Comment by MikeCoder96** [comment]
The procedure is right.
Can you please debug it with Visual Studio? 
The right part you have to check is in PluginInfrastructure\UnamangedExports.cs
![image](https://user-images.githubusercontent.com/50410305/172703192-2720e0a7-a27a-4f29-b2fd-d959bbcf6996.png)

and debug the function `public static void initializeAssembly()`
I'm sure that for some reason the path is wrong and you can check it starting from line 36/37 in the file mentioned before
![image](https://user-images.githubusercontent.com/50410305/172703540-489cfc1d-d271-4dcb-8474-007e712a1ef0.png)

**Comment by thnhmai06** [comment]
> The procedure is right. Can you please debug it with Visual Studio? The right part you have to check is in PluginInfrastructure\UnamangedExports.cs ![image](https://user-images.githubusercontent.com/50410305/172703192-2720e0a7-a27a-4f29-b2fd-d959bbcf6996.png)
> 
> and debug the function `public static void initializeAssembly()` I'm sure that for some reason the path is wrong and you can check it starting from line 36/37 in the file mentioned before ![image](https://user-images.githubusercontent.com/50410305/172703540-489cfc1d-d271-4dcb-8474-007e712a1ef0.png)

Sorry for my late.
I compiled project (Build file) and got this error

![image](https://user-images.githubusercontent.com/62001770/179951715-e2ce8fa3-0a3b-4336-9388-55cb23925f84.png)

When I debug project (added breakpoint), NotePad++ Opened, but nothing happend, RPC didn't working
_I have never debugged/developed anything on VS, so please help me debug._
@MikeCoder96

**Comment by MikeCoder96** [comment]
I will try to fix it ASAP and share here the compiled libs

**Comment by MikeCoder96** [comment]
Fixed and tested in https://github.com/MikeCoder96/NotePad-Discord-Rich-Presence-Plugin/commit/88905db43511b64c0b531b9e26c072c048c6f270

In case it not work, check readme. I've wrote how to start debug.

**Comment by thnhmai06** [comment]
@MikeCoder96 
**Thanks, it's worked correctly!**

![image](https://user-images.githubusercontent.com/62001770/180680899-10509178-fc47-46d2-9b89-f986d53ac5c2.png)

But you should add the last step in `README.md` file to start Discord RP by doing this: 
![image](https://user-images.githubusercontent.com/62001770/180680990-a15783fc-cdce-4093-9fb2-177fb12ddeec.png)
