### ISSUE TITLE
Cannot launch

### ISSUE THREAD

**Issue by lxmmel** [MikeCoder96/NotePad-Discord-Rich-Presence-Plugin#4]
I have tried both versions and it wont work.
Both show the same shit
![image](https://user-images.githubusercontent.com/68713503/184433471-e13f0c4f-b91e-4be1-a0ef-cd5946de55be.png)

**Comment by MikeCoder96** [comment]
Hello, can you please share your version of Notepad++ with the architecture used?

**Comment by MikeCoder96** [comment]
If there is no other info, i will proceed to close the issue
